var dir_cd0bf60e53d1147ccfa0c0babe8425ed =
[
    [ "soc_accept.c", "soc__accept_8c.html", "soc__accept_8c" ],
    [ "soc_bind.c", "soc__bind_8c.html", "soc__bind_8c" ],
    [ "soc_closesocket.c", "soc__closesocket_8c.html", "soc__closesocket_8c" ],
    [ "soc_common.c", "soc__common_8c.html", "soc__common_8c" ],
    [ "soc_common.h", "soc__common_8h.html", "soc__common_8h" ],
    [ "soc_connect.c", "soc__connect_8c.html", "soc__connect_8c" ],
    [ "soc_fcntl.c", "soc__fcntl_8c.html", "soc__fcntl_8c" ],
    [ "soc_gethostbyname.c", "soc__gethostbyname_8c.html", "soc__gethostbyname_8c" ],
    [ "soc_gethostid.c", "soc__gethostid_8c.html", "soc__gethostid_8c" ],
    [ "soc_getpeername.c", "soc__getpeername_8c.html", "soc__getpeername_8c" ],
    [ "soc_getsockname.c", "soc__getsockname_8c.html", "soc__getsockname_8c" ],
    [ "soc_getsockopt.c", "soc__getsockopt_8c.html", "soc__getsockopt_8c" ],
    [ "soc_inet_addr.c", "soc__inet__addr_8c.html", "soc__inet__addr_8c" ],
    [ "soc_inet_aton.c", "soc__inet__aton_8c.html", "soc__inet__aton_8c" ],
    [ "soc_inet_ntoa.c", "soc__inet__ntoa_8c.html", "soc__inet__ntoa_8c" ],
    [ "soc_init.c", "soc__init_8c.html", "soc__init_8c" ],
    [ "soc_ioctl.c", "soc__ioctl_8c.html", "soc__ioctl_8c" ],
    [ "soc_listen.c", "soc__listen_8c.html", "soc__listen_8c" ],
    [ "soc_poll.c", "soc__poll_8c.html", "soc__poll_8c" ],
    [ "soc_recv.c", "soc__recv_8c.html", "soc__recv_8c" ],
    [ "soc_recvfrom.c", "soc__recvfrom_8c.html", "soc__recvfrom_8c" ],
    [ "soc_select.c", "soc__select_8c.html", "soc__select_8c" ],
    [ "soc_send.c", "soc__send_8c.html", "soc__send_8c" ],
    [ "soc_sendto.c", "soc__sendto_8c.html", "soc__sendto_8c" ],
    [ "soc_setsockopt.c", "soc__setsockopt_8c.html", "soc__setsockopt_8c" ],
    [ "soc_shutdown.c", "soc__shutdown_8c.html", "soc__shutdown_8c" ],
    [ "soc_sockatmark.c", "soc__sockatmark_8c.html", "soc__sockatmark_8c" ],
    [ "soc_socket.c", "soc__socket_8c.html", "soc__socket_8c" ]
];